language: java
jdk:
- oraclejdk8

env:
  global:
    - secure: xxx
    - secure: xxx

sudo: required

services:
  - docker

cache:
  directories:
    - '$HOME/.m2'

install: ./mvnw install -DskipTests -Dgpg.skip

script:
  - ./ui/build.sh
  - ./mvnw test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t logzio/apollo:$TRAVIS_COMMIT .;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push logzio/apollo:$TRAVIS_COMMIT;
    fi
