language: java
jdk:
- oraclejdk8

env:
  global:
    - secure: xxx
    - secure: xxx

sudo: required

services:
  - docker

cache:
  directories:
    - '$HOME/.m2'

install: ./mvnw install -DskipTests -Dgpg.skip

script:
  - ./ui/build.sh
  - ./mvnw test

after_success:
  - echo "TRAVIS_BRANCH is $TRAVIS_BRANCH";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
     echo "TRAVIS_BRANCH is $TRAVIS_BRANCH";
    fi
