export const GET_SERVICES_STACK_REQUEST = 'GET_SERVICES_STACK_REQUEST';
export const GET_SERVICES_STACK_SUCCESS = 'GET_SERVICES_STACK_SUCCESS';
export const GET_SERVICES_STACK_FAILURE = 'GET_SERVICES_STACK_FAILURE';
export const SELECT_SERVICE = 'SELECT_SERVICE';
