export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const GET_DEP_ROLE_REQUEST = "GET_DEP_ROLE_REQUEST";
export const GET_DEP_ROLE_SUCCESS = "GET_DEP_ROLE_SUCCESS";
export const GET_DEP_ROLE_FAILURE = "GET_DEP_ROLE_FAILURE";
