export const mock = {
  successful: [
    {
      groupId: null,
      environmentId: 2,
      serviceId: 3,
      deployment: {
        id: 52283,
        environmentId: 2,
        serviceId: 3,
        deployableVersionId: 994485,
        userEmail: 'ifat.regev@logz.io',
        status: 'PENDING',
        sourceVersion: '1e543289a8f2348de34b9f0dc5f292124f62d2a1',
        startedAt: null,
        lastUpdate: null,
        envStatus: null,
        groupName: null,
        deploymentParams: null,
        deploymentMessage: 'PR',
        emergencyDeployment: false,
      },
    },
    {
      groupId: null,
      environmentId: 2,
      serviceId: 69,
      deployment: {
        id: 52284,
        environmentId: 2,
        serviceId: 69,
        deployableVersionId: 994489,
        userEmail: 'ifat.regev@logz.io',
        status: 'PENDING',
        sourceVersion: '1e543289a8f2348de34b9f0dc5f292124f62d2a1',
        startedAt: null,
        lastUpdate: null,
        envStatus: null,
        groupName: null,
        deploymentParams: null,
        deploymentMessage: 'PR',
        emergencyDeployment: false,
      },
    },
    {
      groupId: null,
      environmentId: 2,
      serviceId: 92,
      deployment: {
        id: 52285,
        environmentId: 2,
        serviceId: 92,
        deployableVersionId: 994488,
        userEmail: 'ifat.regev@logz.io',
        status: 'PENDING',
        sourceVersion: '1e543289a8f2348de34b9f0dc5f292124f62d2a1',
        startedAt: null,
        lastUpdate: null,
        envStatus: null,
        groupName: null,
        deploymentParams: null,
        deploymentMessage: 'PR',
        emergencyDeployment: false,
      },
    },
    {
      groupId: null,
      environmentId: 2,
      serviceId: 96,
      deployment: {
        id: 52286,
        environmentId: 2,
        serviceId: 96,
        deployableVersionId: 994491,
        userEmail: 'ifat.regev@logz.io',
        status: 'PENDING',
        sourceVersion: '1e543289a8f2348de34b9f0dc5f292124f62d2a1',
        startedAt: null,
        lastUpdate: null,
        envStatus: null,
        groupName: null,
        deploymentParams: null,
        deploymentMessage: 'PR',
        emergencyDeployment: false,
      },
    },
    {
      groupId: null,
      environmentId: 7,
      serviceId: 3,
      deployment: {
        id: 52287,
        environmentId: 7,
        serviceId: 3,
        deployableVersionId: 994485,
        userEmail: 'ifat.regev@logz.io',
        status: 'PENDING',
        sourceVersion: '9c9cdc775bd31a506539f054591222232794ad5a',
        startedAt: null,
        lastUpdate: null,
        envStatus: null,
        groupName: null,
        deploymentParams: null,
        deploymentMessage: 'PR',
        emergencyDeployment: false,
      },
    },
    {
      groupId: null,
      environmentId: 7,
      serviceId: 69,
      deployment: {
        id: 52288,
        environmentId: 7,
        serviceId: 69,
        deployableVersionId: 994489,
        userEmail: 'ifat.regev@logz.io',
        status: 'PENDING',
        sourceVersion: '9c9cdc775bd31a506539f054591222232794ad5a',
        startedAt: null,
        lastUpdate: null,
        envStatus: null,
        groupName: null,
        deploymentParams: null,
        deploymentMessage: 'PR',
        emergencyDeployment: false,
      },
    },
    {
      groupId: null,
      environmentId: 7,
      serviceId: 96,
      deployment: {
        id: 52289,
        environmentId: 7,
        serviceId: 96,
        deployableVersionId: 994491,
        userEmail: 'ifat.regev@logz.io',
        status: 'PENDING',
        sourceVersion: '9c9cdc775bd31a506539f054591222232794ad5a',
        startedAt: null,
        lastUpdate: null,
        envStatus: null,
        groupName: null,
        deploymentParams: null,
        deploymentMessage: 'PR',
        emergencyDeployment: false,
      },
    },
  ],
  unsuccessful: [
    {
      groupId: null,
      environmentId: 2,
      serviceId: 84,
      exception: {
        cause: null,
        stackTrace: [
          {
            methodName: 'lambda$null$0',
            fileName: 'DeploymentController.java',
            lineNumber: 122,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'forEach',
            fileName: 'Iterable.java',
            lineNumber: 75,
            className: 'java.lang.Iterable',
            nativeMethod: false,
          },
          {
            methodName: 'lambda$addDeployment$1',
            fileName: 'DeploymentController.java',
            lineNumber: 106,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'forEach',
            fileName: 'Iterable.java',
            lineNumber: 75,
            className: 'java.lang.Iterable',
            nativeMethod: false,
          },
          {
            methodName: 'addDeployment',
            fileName: 'DeploymentController.java',
            lineNumber: 106,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: null,
            lineNumber: -1,
            className: 'sun.reflect.GeneratedMethodAccessor569',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: 'DelegatingMethodAccessorImpl.java',
            lineNumber: 43,
            className: 'sun.reflect.DelegatingMethodAccessorImpl',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: 'Method.java',
            lineNumber: 498,
            className: 'java.lang.reflect.Method',
            nativeMethod: false,
          },
          {
            methodName: 'handleReq',
            fileName: 'MethodReqHandler.java',
            lineNumber: 51,
            className: 'org.rapidoid.http.handler.MethodReqHandler',
            nativeMethod: false,
          },
          {
            methodName: 'handleReqAndPostProcess',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 313,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'handleReqMaybeInTx',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 245,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'access$700',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 49,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 211,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler$3',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'PredefinedContextJobWrapper.java',
            lineNumber: 55,
            className: 'org.rapidoid.job.PredefinedContextJobWrapper',
            nativeMethod: false,
          },
          {
            methodName: 'runWorker',
            fileName: 'ThreadPoolExecutor.java',
            lineNumber: 1142,
            className: 'java.util.concurrent.ThreadPoolExecutor',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'ThreadPoolExecutor.java',
            lineNumber: 617,
            className: 'java.util.concurrent.ThreadPoolExecutor$Worker',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'Thread.java',
            lineNumber: 745,
            className: 'java.lang.Thread',
            nativeMethod: false,
          },
        ],
        message: 'DeployableVersion with sha72068f44cedd7378acc584a180dc1533a676b5ac is not applicable on service 84',
        localizedMessage:
          'DeployableVersion with sha72068f44cedd7378acc584a180dc1533a676b5ac is not applicable on service 84',
        suppressed: [],
      },
    },
    {
      groupId: null,
      environmentId: 7,
      serviceId: 84,
      exception: {
        cause: null,
        stackTrace: [
          {
            methodName: 'lambda$null$0',
            fileName: 'DeploymentController.java',
            lineNumber: 122,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'forEach',
            fileName: 'Iterable.java',
            lineNumber: 75,
            className: 'java.lang.Iterable',
            nativeMethod: false,
          },
          {
            methodName: 'lambda$addDeployment$1',
            fileName: 'DeploymentController.java',
            lineNumber: 106,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'forEach',
            fileName: 'Iterable.java',
            lineNumber: 75,
            className: 'java.lang.Iterable',
            nativeMethod: false,
          },
          {
            methodName: 'addDeployment',
            fileName: 'DeploymentController.java',
            lineNumber: 106,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: null,
            lineNumber: -1,
            className: 'sun.reflect.GeneratedMethodAccessor569',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: 'DelegatingMethodAccessorImpl.java',
            lineNumber: 43,
            className: 'sun.reflect.DelegatingMethodAccessorImpl',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: 'Method.java',
            lineNumber: 498,
            className: 'java.lang.reflect.Method',
            nativeMethod: false,
          },
          {
            methodName: 'handleReq',
            fileName: 'MethodReqHandler.java',
            lineNumber: 51,
            className: 'org.rapidoid.http.handler.MethodReqHandler',
            nativeMethod: false,
          },
          {
            methodName: 'handleReqAndPostProcess',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 313,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'handleReqMaybeInTx',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 245,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'access$700',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 49,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 211,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler$3',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'PredefinedContextJobWrapper.java',
            lineNumber: 55,
            className: 'org.rapidoid.job.PredefinedContextJobWrapper',
            nativeMethod: false,
          },
          {
            methodName: 'runWorker',
            fileName: 'ThreadPoolExecutor.java',
            lineNumber: 1142,
            className: 'java.util.concurrent.ThreadPoolExecutor',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'ThreadPoolExecutor.java',
            lineNumber: 617,
            className: 'java.util.concurrent.ThreadPoolExecutor$Worker',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'Thread.java',
            lineNumber: 745,
            className: 'java.lang.Thread',
            nativeMethod: false,
          },
        ],
        message: 'DeployableVersion with sha72068f44cedd7378acc584a180dc1533a676b5ac is not applicable on service 84',
        localizedMessage:
          'DeployableVersion with sha72068f44cedd7378acc584a180dc1533a676b5ac is not applicable on service 84',
        suppressed: [],
      },
    },
    {
      groupId: null,
      environmentId: 7,
      serviceId: 92,
      exception: {
        cause: null,
        stackTrace: [
          {
            methodName: 'addDeployment',
            fileName: 'DeploymentHandler.java',
            lineNumber: 136,
            className: 'io.logz.apollo.deployment.DeploymentHandler',
            nativeMethod: false,
          },
          {
            methodName: 'lambda$null$0',
            fileName: 'DeploymentController.java',
            lineNumber: 125,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'forEach',
            fileName: 'Iterable.java',
            lineNumber: 75,
            className: 'java.lang.Iterable',
            nativeMethod: false,
          },
          {
            methodName: 'lambda$addDeployment$1',
            fileName: 'DeploymentController.java',
            lineNumber: 106,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'forEach',
            fileName: 'Iterable.java',
            lineNumber: 75,
            className: 'java.lang.Iterable',
            nativeMethod: false,
          },
          {
            methodName: 'addDeployment',
            fileName: 'DeploymentController.java',
            lineNumber: 106,
            className: 'io.logz.apollo.controllers.DeploymentController',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: null,
            lineNumber: -1,
            className: 'sun.reflect.GeneratedMethodAccessor569',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: 'DelegatingMethodAccessorImpl.java',
            lineNumber: 43,
            className: 'sun.reflect.DelegatingMethodAccessorImpl',
            nativeMethod: false,
          },
          {
            methodName: 'invoke',
            fileName: 'Method.java',
            lineNumber: 498,
            className: 'java.lang.reflect.Method',
            nativeMethod: false,
          },
          {
            methodName: 'handleReq',
            fileName: 'MethodReqHandler.java',
            lineNumber: 51,
            className: 'org.rapidoid.http.handler.MethodReqHandler',
            nativeMethod: false,
          },
          {
            methodName: 'handleReqAndPostProcess',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 313,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'handleReqMaybeInTx',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 245,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'access$700',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 49,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'AbstractDecoratingHttpHandler.java',
            lineNumber: 211,
            className: 'org.rapidoid.http.handler.AbstractDecoratingHttpHandler$3',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'PredefinedContextJobWrapper.java',
            lineNumber: 55,
            className: 'org.rapidoid.job.PredefinedContextJobWrapper',
            nativeMethod: false,
          },
          {
            methodName: 'runWorker',
            fileName: 'ThreadPoolExecutor.java',
            lineNumber: 1142,
            className: 'java.util.concurrent.ThreadPoolExecutor',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'ThreadPoolExecutor.java',
            lineNumber: 617,
            className: 'java.util.concurrent.ThreadPoolExecutor$Worker',
            nativeMethod: false,
          },
          {
            methodName: 'run',
            fileName: 'Thread.java',
            lineNumber: 745,
            className: 'java.lang.Thread',
            nativeMethod: false,
          },
        ],
        message: 'There is an on-going deployment for this service in this environment with this group',
        localizedMessage: 'There is an on-going deployment for this service in this environment with this group',
        suppressed: [],
      },
    },
  ],
};
